version: "3"
containers:
- name: vscode
  image: codercom/code-server
  cmd: --auth none --disable-telemetry
  ports:
  - 8080
- name: database
  image: sodadata/soda-adventureworks
  ports:
  - 5432
  environment:
    POSTGRES_PASSWORD: secret
