#!/bin/bash 
set -euxo pipefail

apt-get install && apt-get update && apt-get -y install \
    python3-distutils

curl https://bootstrap.pypa.io/get-pip.py | python3

python3 -m pip install --upgrade pip && python3 -m pip install \
    soda-sql-postgresql

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
mkdir /home/coder/soda
mkdir -p /root/.local/share/code-server/User/
cat > /root/.local/share/code-server/User/settings.json <<EOF
{
    "workbench.colorTheme": "Default Dark+",
    "terminal.integrated.cwd": "/home/coder/soda/",
    "terminal.integrated.defaultProfile.linux": "zsh"
}
EOF

exit 0
