#!/bin/bash 
set -euxo pipefail

mkdir -p /home/coder/soda

apt-get install && apt-get update && apt-get -y install \
    python3-distutils

curl https://bootstrap.pypa.io/get-pip.py | python3

python3 -m pip install --upgrade pip && python3 -m pip install \
    soda-sql-postgresql

exit 0
